const fs = require('fs');

const familyData = [
	{
		id: 'g1-1',
		fullName: 'Datuk Aliesyahbana',
		nickname: 'Aliesyahbana',
		gender: 'male',
		birthYear: 1935,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g1-2',
		phone: '',
		address: '',
		bio: 'Pendiri keluarga besar.'
	},
	{
		id: 'g1-2',
		fullName: 'Jiddah Elok',
		nickname: 'Elok',
		gender: 'female',
		birthYear: 1938,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g1-1',
		phone: '',
		address: '',
		bio: 'Istri Datuk Aliesahbana.'
	},
	{
		id: 'g2-1',
		fullName: 'Rofiq',
		nickname: 'Rofiq',
		gender: 'male',
		birthYear: 1958,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-2',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-2',
		fullName: 'Mimi',
		nickname: 'Mimi',
		gender: 'female',
		birthYear: 1960,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-1',
		phone: '',
		address: '',
		bio: 'Istri Rafiq.'
	},
	{
		id: 'g2-3',
		fullName: 'Alm. Farida Agustin',
		nickname: 'Farida',
		gender: 'female',
		birthYear: 1960,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-4',
		phone: '',
		address: '',
		bio: 'Almarhum.'
	},
	{
		id: 'g2-4',
		fullName: 'Alm. Muhammad Thamrin',
		nickname: 'Thamrin',
		gender: 'male',
		birthYear: 1958,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-3',
		phone: '',
		address: '',
		bio: 'Almarhum. Suami Faride Agustin.'
	},
	{
		id: 'g2-5',
		fullName: 'Anwar',
		nickname: 'Anwar',
		gender: 'male',
		birthYear: 1962,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-6',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-6',
		fullName: 'Cici',
		nickname: 'Cici',
		gender: 'female',
		birthYear: 1964,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-5',
		phone: '',
		address: '',
		bio: 'Istri Anwar.'
	},
	{
		id: 'g2-7',
		fullName: 'Ucik Fauziah',
		nickname: 'Ucik',
		gender: 'female',
		birthYear: 1964,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-8',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-8',
		fullName: 'Dudung Kamaludin',
		nickname: 'Dudung K.',
		gender: 'male',
		birthYear: 1962,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-7',
		phone: '',
		address: '',
		bio: 'Suami Mak Raolah.'
	},
	{
		id: 'g2-9',
		fullName: 'Mimiek',
		nickname: 'Mimiek',
		gender: 'female',
		birthYear: 1966,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-10',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-10',
		fullName: 'Rosidi',
		nickname: 'Rosidi',
		gender: 'male',
		birthYear: 1964,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-9',
		phone: '',
		address: '',
		bio: 'Suami Mimiek.'
	},
	{
		id: 'g2-11',
		fullName: 'Marwan',
		nickname: 'Marwan',
		gender: 'male',
		birthYear: 1968,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-12',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-12',
		fullName: 'Elly Jumalia',
		nickname: 'Elly',
		gender: 'female',
		birthYear: 1970,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-11',
		phone: '',
		address: '',
		bio: 'Istri Marwan.'
	},
	{
		id: 'g2-13',
		fullName: 'Nenny Nafisah',
		nickname: 'Nenny',
		gender: 'female',
		birthYear: 1970,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-14',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-14',
		fullName: 'Alm. Aad Harharah',
		nickname: 'Aad',
		gender: 'male',
		birthYear: 1968,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-13',
		phone: '',
		address: '',
		bio: 'Almarhum. Suami Nenny Nafisah.'
	},
	{
		id: 'g2-15',
		fullName: 'Kamaludin',
		nickname: 'Amank',
		gender: 'male',
		birthYear: 1972,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-16',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-16',
		fullName: 'Wardatul Jannah',
		nickname: 'Anna',
		gender: 'female',
		birthYear: 1974,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-15',
		phone: '',
		address: '',
		bio: 'Istri Kamaludin.'
	},
	{
		id: 'g2-17',
		fullName: 'Dudung',
		nickname: 'Dudung',
		gender: 'male',
		birthYear: 1974,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-18',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-18',
		fullName: 'Inung',
		nickname: 'Inung',
		gender: 'female',
		birthYear: 1976,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-17',
		phone: '',
		address: '',
		bio: 'Istri Dudung.'
	},
	{
		id: 'g2-19',
		fullName: 'Mohammad Fikri',
		nickname: 'Fikri',
		gender: 'male',
		birthYear: 1976,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: 'g2-20',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g2-20',
		fullName: 'Yetri Permana Shinta',
		nickname: 'Shinta',
		gender: 'female',
		birthYear: 1974,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g2-19',
		phone: '',
		address: '',
		bio: 'Suami Hadir.'
	},
	{
		id: 'g2-21',
		fullName: 'Haidar',
		nickname: 'Haidar',
		gender: 'male',
		birthYear: 1978,
		photoUrl: '',
		fatherId: 'g1-1',
		motherId: 'g1-2',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-1',
		fullName: 'Ila',
		nickname: 'Ila',
		gender: 'female',
		birthYear: 1985,
		photoUrl: '',
		fatherId: 'g2-1',
		motherId: 'g2-2',
		spouseId: 'g3-2',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-2',
		fullName: 'Suami Ila',
		nickname: 'Suami Ila',
		gender: 'male',
		birthYear: 1983,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-1',
		phone: '',
		address: '',
		bio: 'Suami Ila.'
	},
	{
		id: 'g3-3',
		fullName: 'Ika',
		nickname: 'Ika',
		gender: 'female',
		birthYear: 1987,
		photoUrl: '',
		fatherId: 'g2-1',
		motherId: 'g2-2',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-4',
		fullName: 'Haikal',
		nickname: 'Haikal',
		gender: 'male',
		birthYear: 1990,
		photoUrl: '',
		fatherId: 'g2-1',
		motherId: 'g2-2',
		spouseId: 'g3-5',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-5',
		fullName: 'Istri Haikal',
		nickname: 'Istri Haikal',
		gender: 'female',
		birthYear: 1992,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-4',
		phone: '',
		address: '',
		bio: 'Istri Haikal.'
	},
	{
		id: 'g3-6',
		fullName: 'Alm. Muhammad Faisal',
		nickname: 'Faisal',
		gender: 'male',
		birthYear: 1984,
		photoUrl: '',
		fatherId: 'g2-4',
		motherId: 'g2-3',
		spouseId: null,
		phone: '',
		address: '',
		bio: 'Almarhum.'
	},
	{
		id: 'g3-7',
		fullName: 'Muhammad Fahmi',
		nickname: 'Fahmi',
		gender: 'male',
		birthYear: 1986,
		photoUrl: '',
		fatherId: 'g2-4',
		motherId: 'g2-3',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-8',
		fullName: 'Hernita Natasha',
		nickname: 'Ita',
		gender: 'female',
		birthYear: 1988,
		photoUrl: '',
		fatherId: 'g2-4',
		motherId: 'g2-3',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-9',
		fullName: 'Lia',
		nickname: 'Lia',
		gender: 'female',
		birthYear: 1988,
		photoUrl: '',
		fatherId: 'g2-5',
		motherId: 'g2-6',
		spouseId: 'g3-10',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-10',
		fullName: 'Suami Lia',
		nickname: 'Suami Lia',
		gender: 'male',
		birthYear: 1986,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-9',
		phone: '',
		address: '',
		bio: 'Suami Lia.'
	},
	{
		id: 'g3-11',
		fullName: 'Safier',
		nickname: 'Safier',
		gender: 'male',
		birthYear: 1990,
		photoUrl: '',
		fatherId: 'g2-5',
		motherId: 'g2-6',
		spouseId: 'g3-12',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-12',
		fullName: 'Istri Safier',
		nickname: 'Istri Safier',
		gender: 'female',
		birthYear: 1992,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-11',
		phone: '',
		address: '',
		bio: 'Istri Safier.'
	},
	{
		id: 'g3-13',
		fullName: 'Alm. Amar',
		nickname: 'Amar',
		gender: 'male',
		birthYear: 1992,
		photoUrl: '',
		fatherId: 'g2-5',
		motherId: 'g2-6',
		spouseId: 'g3-14',
		phone: '',
		address: '',
		bio: 'Almarhum.'
	},
	{
		id: 'g3-14',
		fullName: 'Istri Alm. Amar',
		nickname: 'Istri Amar',
		gender: 'female',
		birthYear: 1994,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-13',
		phone: '',
		address: '',
		bio: 'Istri Alm. Amar.'
	},
	{
		id: 'g3-15',
		fullName: 'Fikran',
		nickname: 'Fikran',
		gender: 'male',
		birthYear: 1995,
		photoUrl: '',
		fatherId: 'g2-5',
		motherId: 'g2-6',
		spouseId: 'g3-16',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-16',
		fullName: 'Caca',
		nickname: 'Caca',
		gender: 'female',
		birthYear: 1997,
		photoUrl: '',
		fatherId: 'g2-5',
		motherId: 'g2-6',
		spouseId: 'g3-15',
		phone: '',
		address: '',
		bio: 'Istri Fikran.'
	},
	{
		id: 'g3-17',
		fullName: 'Vira Qonita',
		nickname: 'Vira',
		gender: 'female',
		birthYear: 1988,
		photoUrl: '',
		fatherId: 'g2-8',
		motherId: 'g2-7',
		spouseId: 'g3-18',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-18',
		fullName: 'Sugeng Afianto',
		nickname: 'Sugeng',
		gender: 'male',
		birthYear: 1986,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-17',
		phone: '',
		address: '',
		bio: 'Suami Vira Qonita.'
	},
	{
		id: 'g3-19',
		fullName: 'Hafidz',
		nickname: 'Hafidz',
		gender: 'male',
		birthYear: 1990,
		photoUrl: '',
		fatherId: 'g2-8',
		motherId: 'g2-7',
		spouseId: 'g3-20',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-20',
		fullName: 'Ayu',
		nickname: 'Ayu',
		gender: 'female',
		birthYear: 1992,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-19',
		phone: '',
		address: '',
		bio: 'Istri Harlida.'
	},
	{
		id: 'g3-21',
		fullName: 'Helmi',
		nickname: 'Helmi',
		gender: 'male',
		birthYear: 1993,
		photoUrl: '',
		fatherId: 'g2-8',
		motherId: 'g2-7',
		spouseId: 'g3-22',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-22',
		fullName: 'Visca',
		nickname: 'Visca',
		gender: 'female',
		birthYear: 1995,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-21',
		phone: '',
		address: '',
		bio: 'Istri Hermi.'
	},
	{
		id: 'g3-23',
		fullName: 'Hisyam',
		nickname: 'Hisyam',
		gender: 'male',
		birthYear: 1988,
		photoUrl: '',
		fatherId: 'g2-10',
		motherId: 'g2-9',
		spouseId: 'g3-24',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-24',
		fullName: 'Indah',
		nickname: 'Indah',
		gender: 'female',
		birthYear: 1990,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-23',
		phone: '',
		address: '',
		bio: 'Istri Hiyam.'
	},
	{
		id: 'g3-25',
		fullName: 'Nabil',
		nickname: 'Nabil',
		gender: 'male',
		birthYear: 1990,
		photoUrl: '',
		fatherId: 'g2-10',
		motherId: 'g2-9',
		spouseId: 'g3-26',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-26',
		fullName: 'Lulu',
		nickname: 'Lulu',
		gender: 'female',
		birthYear: 1992,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-25',
		phone: '',
		address: '',
		bio: 'Istri Nabil.'
	},
	{
		id: 'g3-27',
		fullName: 'Qonita',
		nickname: 'Qonita',
		gender: 'female',
		birthYear: 1993,
		photoUrl: '',
		fatherId: 'g2-10',
		motherId: 'g2-9',
		spouseId: 'g3-28',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-28',
		fullName: 'Amul',
		nickname: 'Amul',
		gender: 'male',
		birthYear: 1991,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-27',
		phone: '',
		address: '',
		bio: 'Suami Qonita.'
	},
	{
		id: 'g3-29',
		fullName: 'Iqbal',
		nickname: 'Iqbal',
		gender: 'male',
		birthYear: 1996,
		photoUrl: '',
		fatherId: 'g2-10',
		motherId: 'g2-9',
		spouseId: 'g3-30',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-30',
		fullName: 'Fera',
		nickname: 'Fera',
		gender: 'female',
		birthYear: 1998,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-29',
		phone: '',
		address: '',
		bio: 'Istri Iqbal.'
	},
	{
		id: 'g3-31',
		fullName: 'Ratih Ardhini',
		nickname: 'Dini',
		gender: 'female',
		birthYear: 1992,
		photoUrl: '',
		fatherId: 'g2-11',
		motherId: 'g2-12',
		spouseId: 'g3-32',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-32',
		fullName: 'Eros Sidney',
		nickname: 'Eros',
		gender: 'male',
		birthYear: 1990,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-31',
		phone: '',
		address: '',
		bio: 'Suami Ratih Ardhini.'
	},
	{
		id: 'g3-33',
		fullName: 'Melfri Gazza',
		nickname: 'Melfri',
		gender: 'male',
		birthYear: 1994,
		photoUrl: '',
		fatherId: 'g2-11',
		motherId: 'g2-12',
		spouseId: 'g3-34',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-34',
		fullName: 'Safira Yulia',
		nickname: 'Safira',
		gender: 'female',
		birthYear: 1996,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-33',
		phone: '',
		address: '',
		bio: 'Istri Melfri Gazza.'
	},
	{
		id: 'g3-35',
		fullName: 'Meldiego Armando',
		nickname: 'Diego',
		gender: 'male',
		birthYear: 1997,
		photoUrl: '',
		fatherId: 'g2-11',
		motherId: 'g2-12',
		spouseId: 'g3-36',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-36',
		fullName: 'Ravena Pringga',
		nickname: 'Ravena',
		gender: 'female',
		birthYear: 1999,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-35',
		phone: '',
		address: '',
		bio: 'Istri Merdiego Armando.'
	},
	{
		id: 'g3-37',
		fullName: 'Najlah Harharah',
		nickname: 'Najlah',
		gender: 'female',
		birthYear: 1993,
		photoUrl: '',
		fatherId: 'g2-14',
		motherId: 'g2-13',
		spouseId: 'g3-38',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-38',
		fullName: 'Aryza Wisnu Wardhana',
		nickname: 'Aryza',
		gender: 'male',
		birthYear: 1991,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-37',
		phone: '',
		address: '',
		bio: 'Suami Najlah Harharah.'
	},
	{
		id: 'g3-39',
		fullName: 'Najmah Harharah',
		nickname: 'Najmah',
		gender: 'female',
		birthYear: 1996,
		photoUrl: '',
		fatherId: 'g2-14',
		motherId: 'g2-13',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-40',
		fullName: 'Nawal Harharah',
		nickname: 'Nawal',
		gender: 'female',
		birthYear: 1998,
		photoUrl: '',
		fatherId: 'g2-14',
		motherId: 'g2-13',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-41',
		fullName: 'Dina Kusumawardhani',
		nickname: 'Dina',
		gender: 'female',
		birthYear: 1996,
		photoUrl: '',
		fatherId: 'g2-15',
		motherId: 'g2-16',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-42',
		fullName: 'M. Melvin Mauludin',
		nickname: 'Melvin',
		gender: 'male',
		birthYear: 1998,
		photoUrl: '',
		fatherId: 'g2-15',
		motherId: 'g2-16',
		spouseId: 'g3-43',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-43',
		fullName: 'Hernanda Ayu Amalia',
		nickname: 'Hernanda',
		gender: 'female',
		birthYear: 2000,
		photoUrl: '',
		fatherId: 'g2-15',
		motherId: 'g2-16',
		spouseId: 'g3-42',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-44',
		fullName: 'Dewi Faradiba',
		nickname: 'Fara',
		gender: 'female',
		birthYear: 2002,
		photoUrl: '',
		fatherId: 'g2-15',
		motherId: 'g2-16',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-45',
		fullName: 'Yanuar',
		nickname: 'Yanuar',
		gender: 'male',
		birthYear: 1998,
		photoUrl: '',
		fatherId: 'g2-17',
		motherId: 'g2-18',
		spouseId: 'g3-46',
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-46',
		fullName: 'Anet',
		nickname: 'Anet',
		gender: 'female',
		birthYear: 2000,
		photoUrl: '',
		fatherId: null,
		motherId: null,
		spouseId: 'g3-45',
		phone: '',
		address: '',
		bio: 'Istri Yanuar.'
	},
	{
		id: 'g3-47',
		fullName: 'Octa',
		nickname: 'Octa',
		gender: 'male',
		birthYear: 2000,
		photoUrl: '',
		fatherId: 'g2-17',
		motherId: 'g2-18',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-48',
		fullName: 'Athira',
		nickname: 'Athira',
		gender: 'female',
		birthYear: 2003,
		photoUrl: '',
		fatherId: 'g2-17',
		motherId: 'g2-18',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-49',
		fullName: 'Mohammad Rasas Aufar',
		nickname: 'Rasas',
		gender: 'male',
		birthYear: 2000,
		photoUrl: '',
		fatherId: 'g2-20',
		motherId: 'g2-19',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g3-50',
		fullName: 'Syaula Shofura',
		nickname: 'Syaula',
		gender: 'female',
		birthYear: 2002,
		photoUrl: '',
		fatherId: 'g2-20',
		motherId: 'g2-19',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-1',
		fullName: 'Anak 1 Ila',
		nickname: 'Anak 1 Ila',
		gender: 'female',
		birthYear: 2010,
		photoUrl: '',
		fatherId: 'g3-2',
		motherId: 'g3-1',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-2',
		fullName: 'Anak 2 Ila',
		nickname: 'Anak 2 Ila',
		gender: 'male',
		birthYear: 2012,
		photoUrl: '',
		fatherId: 'g3-2',
		motherId: 'g3-1',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-3',
		fullName: 'Anak 1 Ika',
		nickname: 'Anak 1 Ika',
		gender: 'male',
		birthYear: 2015,
		photoUrl: '',
		fatherId: 'g3-2',
		motherId: 'g3-1',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-4',
		fullName: 'Anak 2 Ika',
		nickname: 'Anak 2 Ika',
		gender: 'male',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-2',
		motherId: 'g3-1',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-5',
		fullName: 'Anak 1 Haikal',
		nickname: 'Anak 1 Haikal',
		gender: 'female',
		birthYear: 2015,
		photoUrl: '',
		fatherId: 'g3-4',
		motherId: 'g3-5',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-6',
		fullName: 'Anak 2 Haikal',
		nickname: 'Anak 2 Haikal',
		gender: 'male',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-4',
		motherId: 'g3-5',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-7',
		fullName: 'Alysha Nindya Fathitah',
		nickname: 'Alysha',
		gender: 'female',
		birthYear: 2012,
		photoUrl: '',
		fatherId: null,
		motherId: 'g3-8',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-8',
		fullName: 'Muchammad Mufasa Thamrin',
		nickname: 'Mufasa',
		gender: 'male',
		birthYear: 2014,
		photoUrl: '',
		fatherId: null,
		motherId: 'g3-8',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-9',
		fullName: 'Muhammad Mahesa Thamrin',
		nickname: 'Mahesa',
		gender: 'male',
		birthYear: 2016,
		photoUrl: '',
		fatherId: null,
		motherId: 'g3-8',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-10',
		fullName: 'Azzam',
		nickname: 'Azzam',
		gender: 'male',
		birthYear: 2016,
		photoUrl: '',
		fatherId: 'g3-11',
		motherId: 'g3-12',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-11',
		fullName: 'Anak 1 Alm. Amar',
		nickname: 'Anak 1 Amar',
		gender: 'male',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-13',
		motherId: 'g3-14',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-12',
		fullName: 'Shakira',
		nickname: 'Shakira',
		gender: 'female',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-9',
		motherId: 'g3-10',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-13',
		fullName: 'Sarah',
		nickname: 'Sarah',
		gender: 'female',
		birthYear: 2012,
		photoUrl: '',
		fatherId: 'g3-18',
		motherId: 'g3-17',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-14',
		fullName: 'Sanas',
		nickname: 'Sanas',
		gender: 'female',
		birthYear: 2014,
		photoUrl: '',
		fatherId: 'g3-18',
		motherId: 'g3-17',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-15',
		fullName: 'Shidai',
		nickname: 'Shidai',
		gender: 'male',
		birthYear: 2017,
		photoUrl: '',
		fatherId: 'g3-18',
		motherId: 'g3-17',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-16',
		fullName: 'Syahdan',
		nickname: 'Syahdan',
		gender: 'male',
		birthYear: 2015,
		photoUrl: '',
		fatherId: 'g3-19',
		motherId: 'g3-20',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-17',
		fullName: 'Aulia',
		nickname: 'Aulia',
		gender: 'female',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-19',
		motherId: 'g3-20',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-18',
		fullName: 'Adam',
		nickname: 'Adam',
		gender: 'male',
		birthYear: 2017,
		photoUrl: '',
		fatherId: 'g3-21',
		motherId: 'g3-22',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-19',
		fullName: 'Syifa',
		nickname: 'Syifa',
		gender: 'female',
		birthYear: 2020,
		photoUrl: '',
		fatherId: 'g3-21',
		motherId: 'g3-22',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-19',
		fullName: 'Alin',
		nickname: 'Alin',
		gender: 'female',
		birthYear: 2012,
		photoUrl: '',
		fatherId: 'g3-23',
		motherId: 'g3-24',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-20',
		fullName: 'Andin',
		nickname: 'Andin',
		gender: 'female',
		birthYear: 2014,
		photoUrl: '',
		fatherId: 'g3-23',
		motherId: 'g3-24',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-21',
		fullName: 'Hafidzah',
		nickname: 'Hafidzah',
		gender: 'female',
		birthYear: 2016,
		photoUrl: '',
		fatherId: 'g3-23',
		motherId: 'g3-24',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-22',
		fullName: 'Anak 4 Hisyam',
		nickname: 'Anak 4 Hisyam',
		gender: 'female',
		birthYear: 2019,
		photoUrl: '',
		fatherId: 'g3-23',
		motherId: 'g3-24',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-23',
		fullName: 'Aluna',
		nickname: 'Aluna',
		gender: 'female',
		birthYear: 2014,
		photoUrl: '',
		fatherId: 'g3-25',
		motherId: 'g3-26',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-24',
		fullName: 'Arka',
		nickname: 'Arka',
		gender: 'male',
		birthYear: 2016,
		photoUrl: '',
		fatherId: 'g3-25',
		motherId: 'g3-26',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-25',
		fullName: 'Alana',
		nickname: 'Alana',
		gender: 'female',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-25',
		motherId: 'g3-26',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-26',
		fullName: 'Alena',
		nickname: 'Alena',
		gender: 'female',
		birthYear: 2021,
		photoUrl: '',
		fatherId: 'g3-25',
		motherId: 'g3-26',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-27',
		fullName: 'Khansa',
		nickname: 'Khansa',
		gender: 'female',
		birthYear: 2016,
		photoUrl: '',
		fatherId: 'g3-28',
		motherId: 'g3-27',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-28',
		fullName: 'Aira',
		nickname: 'Aira',
		gender: 'female',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-28',
		motherId: 'g3-27',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-29',
		fullName: 'Ocin',
		nickname: 'Ocin',
		gender: 'female',
		birthYear: 2021,
		photoUrl: '',
		fatherId: 'g3-28',
		motherId: 'g3-27',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-30',
		fullName: 'Anak 1 Iqbal',
		nickname: 'Anak 1 Iqbal',
		gender: 'male',
		birthYear: 2020,
		photoUrl: '',
		fatherId: 'g3-29',
		motherId: 'g3-30',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-31',
		fullName: 'Adelarde Idris Rafiquzzikri',
		nickname: 'Idris',
		gender: 'female',
		birthYear: 2016,
		photoUrl: '',
		fatherId: 'g3-32',
		motherId: 'g3-31',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-32',
		fullName: 'Musa Abdul Matin',
		nickname: 'Musa',
		gender: 'male',
		birthYear: 2019,
		photoUrl: '',
		fatherId: 'g3-32',
		motherId: 'g3-31',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-33',
		fullName: 'Arunala Renjana Maryam',
		nickname: 'Nala',
		gender: 'female',
		birthYear: 2020,
		photoUrl: '',
		fatherId: 'g3-33',
		motherId: 'g3-34',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-34',
		fullName: 'Rael Isa Armando',
		nickname: 'Rael',
		gender: 'male',
		birthYear: 2022,
		photoUrl: '',
		fatherId: 'g3-35',
		motherId: 'g3-36',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-35',
		fullName: 'Lasya Aiza Wardhana',
		nickname: 'Lasya',
		gender: 'female',
		birthYear: 2018,
		photoUrl: '',
		fatherId: 'g3-38',
		motherId: 'g3-37',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-36',
		fullName: 'Elhan Rafan Wardhana',
		nickname: 'Elhan',
		gender: 'male',
		birthYear: 2021,
		photoUrl: '',
		fatherId: 'g3-38',
		motherId: 'g3-37',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	},
	{
		id: 'g4-37',
		fullName: 'Xavier',
		nickname: 'Xavier',
		gender: 'male',
		birthYear: 2023,
		photoUrl: '',
		fatherId: 'g3-45',
		motherId: 'g3-46',
		spouseId: null,
		phone: '',
		address: '',
		bio: ''
	}
];

const getGenerationString = (id) => {
	if (id.startsWith('g1')) return '1st Generation - Grandparent';
	if (id.startsWith('g2')) return '2nd Generation - Parent';
	if (id.startsWith('g3')) return '3rd Generation - Child';
	if (id.startsWith('g4')) return '4th Generation - Grandchild';
	return 'Unknown Generation';
};

const getAvatar = (name) =>
	`https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=random&color=ffffff&size=200`;

const members = familyData.map((m) => {
	const father = familyData.find((f) => f.id === m.fatherId);
	const mother = familyData.find((f) => f.id === m.motherId);
	const spouse = familyData.find((f) => f.id === m.spouseId);
	const children = familyData.filter((c) => c.fatherId === m.id || c.motherId === m.id);

	const family = [];
	if (father)
		family.push({
			relation: 'Father',
			name: father.fullName,
			image: father.photoUrl || getAvatar(father.fullName)
		});
	if (mother)
		family.push({
			relation: 'Mother',
			name: mother.fullName,
			image: mother.photoUrl || getAvatar(mother.fullName)
		});
	if (spouse)
		family.push({
			relation: 'Spouse',
			name: spouse.fullName,
			image: spouse.photoUrl || getAvatar(spouse.fullName)
		});
	children.forEach((c) => {
		family.push({
			relation: c.gender === 'male' ? 'Son' : 'Daughter',
			name: c.fullName,
			image: c.photoUrl || getAvatar(c.fullName)
		});
	});

	return {
		id: m.id,
		name: m.fullName,
		nickname: m.nickname,
		generation: getGenerationString(m.id),
		description: m.bio || `Member of the family. ${m.fullName} was born in ${m.birthYear}.`,
		born: m.birthYear ? m.birthYear.toString() : '-',
		occupation: 'Not specified',
		residence: m.address || 'Indonesia',
		memberSince: '2026',
		image: m.photoUrl || getAvatar(m.fullName),
		timeline: [
			{
				year: m.birthYear ? m.birthYear.toString() : '-',
				icon: 'child_care',
				title: 'Born',
				description: `${m.fullName} was born in ${m.birthYear}.`
			}
		],
		family: family,
		photos: [
			'https://lh3.googleusercontent.com/aida-public/AB6AXuDdObqBMekBf6AnGsif-tJdn-XjtdwrY1fiNGTBeou4DNQ8waQfKBTSAuyKD-SHrPjsLFLsagX1CHRtJm0RPuZJQnOtvI_UD1qlsTYTa-MBRe1avMQO5vROJLQyWOmEmvYacvAeQhPZXDGxgEYN2p9rlr8Vd8jpVxEzzJ8aaWzzkLxX5zv5zrzWDOS7_jWH19FKaInFZsMBHHMmBNy3xHpQuglH0073_kkMpZguu94QkpDeAt6YcUWRQyuNrLnXTxSgCVZc952bUZE',
			'https://lh3.googleusercontent.com/aida-public/AB6AXuAjke1cteXNIY9gMW_iHn8T8z1-gEXp3cNPILmtjfxI9_3AUONgqaGUC095DYZtbfZoSEfywn_CkYiHoQ8mEZYOf-L4kZJKeFL9M3TmC4sF2HzWC9q0hdufgS2jJwLuekz_0kSi3Bx3PRhQnx6Ley3CX7SBwrhq0EFQpTWFjiiJBa5FEax7hSAxAxUBH3FX6r-vRtvlGZSMasEsNzHtSUunlxvwfi13Dfo0assNhhj2Lhno7I7_dq75FhctDNRtp2lc3yw174aO-a4',
			'https://lh3.googleusercontent.com/aida-public/AB6AXuBBsRSFZ3bEwjx2FgtIHTqOlg5dzLT0Fb-cBJSpMPJ7J5u4niv7xw2UJp3hDVbhpL3uFrq7fF4V9vWExbSs-SMEda5B0ZIwHRJszNKt7x6_MFfD07gyJbTqqjCLrZBVKC9XOJY6hFA24oA0Q56L0r4SS6oF9DGFdDzdet6Yyd4EKe65SJ4THFF-gXY8DAJiTt30z_aQUEEhF-nVlDW2UETd4jLlAIKRL0bfUTGui3A2h0ZNfK3kYi6Q_JnDEsKqKVEkNwJvZsP4Bnw'
		]
	};
});

fs.writeFileSync('src/lib/data/members.json', JSON.stringify(members, null, '\t'));
console.log('JSON regenerated successfully.');
